export EEG_BCI_WS=$PWD
export EEG_BCI_ARTIFACTS_DIR=$EEG_BCI_WS/artifacts
export EEG_BCI_BUILD_DIR=$EEG_BCI_ARTIFACTS_DIR/build
export EEG_BCI_INSTALL_DIR=$EEG_BCI_ARTIFACTS_DIR/install
export EEG_BCI_DATASETS_DIR=$EEG_BCI_WS/datasets
export EEG_BCI_SRC_DIR=$EEG_BCI_WS/src
export EEG_BCI_MODELS_DIR=$EEG_BCI_WS/models


mkdir -p $EEG_BCI_WS \
 $EEG_BCI_ARTIFACTS_DIR \
 $EEG_BCI_BUILD_DIR \
 $EEG_BCI_INSTALL_DIR \
 $EEG_BCI_DATASETS_DIR \
 $EEG_BCI_SRC_DIR \
 $EEG_BCI_MODELS_DIR
